name: Deploy Scientific Calculator
  hosts: localhost
  become: true
  tasks:
    - name: Pull Docker Image from Docker Hub
      community.docker.docker_image:
        name: "substobeme/spe_calculator:latest"
        source: pull

    - name: Run Docker Container
      community.docker.docker_container:
        name: scientific_calculator
        image: "substobeme/spe_calculator:latest"
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
